### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by barneyhill**
Hi Georgios, 

I've gone ahead and made a few changes to the annotation script. I'm sure i've added more things but we've:
- Removed filtering on MANE select
- Parameterised the script
- Reading in SpliceAI INFO fields with gene specific scores (results of this function have been independently verified)

Would you be able to take a look at the changed script and see if everything looks good to you?

Many Thanks,
Barney

### CODE REVIEW

**Comment by astheeggeggs** [comment]
Thanks @barneyhill ! Re: the canonical transcript - this'll end up being the same when MANE select is defined (we pulled vep to 105 to ensure MANE select and 'canonical' line up where MANE select is defined - see here https://www.ensembl.org/info/genome/genebuild/canonical.html), so in effect it'll just allow us to assign 'damaging missense' variants to a few more genes (that otherwise wouldn't have a 'canonical transcript' defined at all). The spliceAI piece is a bug, now fixed!

**Comment by giorkala** [comment]
Thanks @barneyhill, nice improvement and quite neat! 

It looks great to me, and I only have a few comments:
* I hadn't noticed SpliceAI can give multiple scores for the same gene, so that's a great fix. 
* At that point, when we do the splitting to  `["GENE","max_DS"]` ([line 175](https://github.com/BRaVa-genetics/variant-annotation-python/blob/barney-annot/scripts/brava_create_annot.py#L175)), I got an error, possibly because of empty SpliceAI fields. I avoided that by adding `spliceai_df = spliceai_df[spliceai_df.spliceai_pairs.notna()]` (which Barney tests afterwards anyway).
* Also, similarly to how we load `args.vep` we could add options for `args.spliceai`. In our case (where we lacked a few columns) I needed this
```
spliceai_df = pd.read_csv("sandbox/chr22.SpliceAI.gz", sep='\t', comment='#', header=None, names=["CHROM", "POS", "ID", "REF", "ALT", "INFO"], na_values='.' )
spliceai_df.set_index( spliceai_df.CHROM + ":" + spliceai_df.POS.astype(str), inplace=True )
```
* Finally, and for the record in case anyone has a similar issue, I once (just for chr19) faced the following error while reading the VEP table.
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 101264: invalid start byte
```
I had no clue why, but one work-around was to add encoding='cp1252' in the `pd.read_csv` command, so we could add this as a comment for future users.

Overall, nothing crucial so please go on with the merge.
Georgios

**Comment by barneyhill** [comment]
Thanks for checking the code! Added a couple of changes. Could there potentially be an issue where
`spliceai_df.set_index( spliceai_df.CHROM + ":" + spliceai_df.POS.astype(str), inplace=True )`
is non-unique in the case of more than one variant at a single CHR:POS such as:
```
chr21   5033478 chr21:5033478:G:A   G   A   .   .   SpliceAI=A|ENSG00000277117---ENSG00000277117.5---ENST00000623960.4---yes---protein_coding---NM_001363770.2|0.00|0.00|0.00|0.15|-35|36|36|-35
chr21   5033478 chr21:5033478:G:T   G   T   .   .   SpliceAI=T|ENSG00000277117---ENSG00000277117.5---ENST00000623960.4---yes---protein_coding---NM_001363770.2|0.00|0.00|0.00|0.11|-35|36|36|-35
```

Just to clarify I can't specically see if this would cause an issue, just wondering if there could be some unintended behaviour with non-unique indexes.

**Comment by giorkala** [comment]
sorry, you're right! we'd need 
```
 spliceai_df.ID = spliceai_df.CHROM + ":" + spliceai_df.POS.astype(str)  + ":" + spliceai_df.REF + ":" + spliceai_df.ALT 
```
or whatever the format in the format in `args.vep_snp_id_col`

**Comment by barneyhill** [comment]
nice added that in

**Pull request merged**
